### ISSUE TITLE
Sample Apk

### ISSUE THREAD

**Issue by dead8309** [Japskiddin/DebugLogger#1]
Nice project.
It would be nice if you attach a sample apk or screenshot of app.

You can also use github actions. Here's a piece of code I generally use.

```yaml
name: Test Apk

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build Apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup jdk-17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble Debug
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/**.apk
```
